sudo: true
language: clojure

# https://github.com/technomancy/leiningen/issues/2014#issuecomment-153829977
before_install: yes y | sudo lein upgrade

script:
  - lein test-all
after_success: ./scripts/after_success.sh 2>&1 | sed "s/$GITHUB_TOKEN/<hidden github token>/"
notifications:
  email: false
